-- CampusFix Database Schema
-- PostgreSQL
-- Revised to match the CampusFix product structure and workflow.

-- ============================================================
-- 1. LOOKUP / ORGANIZATION TABLES
-- ============================================================

CREATE TABLE public.roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE public.student_types (
    student_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE public.departments (
    department_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.statuses (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE public.priorities (
    priority_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    level integer NOT NULL UNIQUE CHECK (level BETWEEN 1 AND 4)
);

CREATE TABLE public.issue_types (
    issue_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE,
    description text
);

CREATE TABLE public.area_types (
    area_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

-- ============================================================
-- 2. USERS
-- ============================================================

CREATE TABLE public.users (
    user_id uuid PRIMARY KEY,
    first_name varchar NOT NULL,
    last_name varchar NOT NULL,
    email varchar NOT NULL UNIQUE
        CHECK (email LIKE '%@caldwell.edu'),
    phone varchar,
    role_id integer NOT NULL
        REFERENCES public.roles(role_id),
    student_type_id integer
        REFERENCES public.student_types(student_type_id),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- A staff/admin user can belong to one or more departments.
CREATE TABLE public.user_departments (
    user_department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL
        REFERENCES public.users(user_id),
    department_id integer NOT NULL
        REFERENCES public.departments(department_id),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, department_id)
);

-- ============================================================
-- 3. CAMPUS LOCATION HIERARCHY
-- ============================================================

CREATE TABLE public.buildings (
    building_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL UNIQUE
);

CREATE TABLE public.floors (
    floor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id integer NOT NULL
        REFERENCES public.buildings(building_id),
    floor_number varchar NOT NULL,
    UNIQUE (building_id, floor_number)
);

-- Building is derived through floor_id.
-- This avoids inconsistent building/floor combinations.
CREATE TABLE public.locations (
    location_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    floor_id integer
        REFERENCES public.floors(floor_id),
    room_number varchar,
    exact_description text,
    area_type_id integer
        REFERENCES public.area_types(area_type_id),
    latitude numeric CHECK (
        latitude BETWEEN -90 AND 90 OR latitude IS NULL
    ),
    longitude numeric CHECK (
        longitude BETWEEN -180 AND 180 OR longitude IS NULL
    )
);

-- ============================================================
-- 4. TICKETS
-- ============================================================

CREATE TABLE public.tickets (
    ticket_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Requester
    reported_by uuid NOT NULL
        REFERENCES public.users(user_id),

    -- Original user submission
    original_text text NOT NULL
        CHECK (length(trim(original_text)) > 0),

    title varchar NOT NULL
        CHECK (length(trim(title)) > 0),

    description text,

    -- Effective/approved classification
    department_id integer
        REFERENCES public.departments(department_id),

    issue_type_id integer
        REFERENCES public.issue_types(issue_type_id),

    priority_id integer
        REFERENCES public.priorities(priority_id),

    status_id integer NOT NULL
        REFERENCES public.statuses(status_id),

    location_id integer
        REFERENCES public.locations(location_id),

    -- AI suggestions
    ai_suggested_department_id integer
        REFERENCES public.departments(department_id),

    ai_suggested_issue_type_id integer
        REFERENCES public.issue_types(issue_type_id),

    ai_suggested_priority_id integer
        REFERENCES public.priorities(priority_id),

    ai_confidence numeric(5,4)
        CHECK (ai_confidence BETWEEN 0 AND 1),

    ai_routing_status varchar NOT NULL DEFAULT 'PENDING'
        CHECK (
            ai_routing_status IN (
                'PENDING',
                'AUTO_ROUTED',
                'NEEDS_REVIEW',
                'ACCEPTED',
                'OVERRIDDEN',
                'FAILED'
            )
        ),

    -- Resolution
    resolution_notes text,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    closed_at timestamptz,

    -- User-side deletion should be soft deletion
    deleted_at timestamptz
);

-- ============================================================
-- 5. TICKET COMMENTS / NOTES
-- ============================================================

CREATE TABLE public.comments (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL
        REFERENCES public.tickets(ticket_id),
    user_id uuid NOT NULL
        REFERENCES public.users(user_id),
    message text NOT NULL
        CHECK (length(trim(message)) > 0),
    is_internal boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz
);

-- ============================================================
-- 6. ATTACHMENTS
-- ============================================================

CREATE TABLE public.attachments (
    attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL
        REFERENCES public.tickets(ticket_id),
    uploaded_by uuid NOT NULL
        REFERENCES public.users(user_id),
    file_name varchar NOT NULL,
    file_url text NOT NULL,
    file_type varchar,
    file_size_bytes bigint
        CHECK (file_size_bytes IS NULL OR file_size_bytes > 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 7. ASSIGNMENTS
-- ============================================================

CREATE TABLE public.ticket_assignments (
    assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL
        REFERENCES public.tickets(ticket_id),
    assigned_to uuid NOT NULL
        REFERENCES public.users(user_id),
    assigned_by uuid NOT NULL
        REFERENCES public.users(user_id),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    unassigned_at timestamptz
);

-- Prevent multiple currently-active assignments for one ticket.
CREATE UNIQUE INDEX ux_ticket_one_active_assignment
ON public.ticket_assignments(ticket_id)
WHERE unassigned_at IS NULL;

-- ============================================================
-- 8. TICKET HISTORY / AUDIT LOG
-- ============================================================

CREATE TABLE public.ticket_history (
    history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL
        REFERENCES public.tickets(ticket_id),
    changed_by uuid
        REFERENCES public.users(user_id),
    action varchar NOT NULL,
    field_name varchar,
    old_value text,
    new_value text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 9. REOPEN REQUESTS
-- ============================================================

CREATE TABLE public.ticket_reopen_requests (
    request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL
        REFERENCES public.tickets(ticket_id),
    requested_by uuid NOT NULL
        REFERENCES public.users(user_id),
    requested_at timestamptz NOT NULL DEFAULT now(),

    decision varchar NOT NULL DEFAULT 'PENDING'
        CHECK (
            decision IN (
                'PENDING',
                'APPROVED',
                'DENIED'
            )
        ),

    decided_by uuid
        REFERENCES public.users(user_id),

    decided_at timestamptz,
    reason text,

    CHECK (
        (decision = 'PENDING' AND decided_by IS NULL AND decided_at IS NULL)
        OR
        (decision IN ('APPROVED', 'DENIED')
         AND decided_by IS NOT NULL
         AND decided_at IS NOT NULL)
    )
);

-- ============================================================
-- 10. NOTIFICATIONS
-- ============================================================

CREATE TABLE public.notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL
        REFERENCES public.users(user_id),
    ticket_id bigint
        REFERENCES public.tickets(ticket_id),
    type varchar NOT NULL,
    message text NOT NULL,
    read_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- 11. INDEXES
-- ============================================================

CREATE INDEX ix_tickets_reported_by
    ON public.tickets(reported_by);

CREATE INDEX ix_tickets_department
    ON public.tickets(department_id);

CREATE INDEX ix_tickets_status
    ON public.tickets(status_id);

CREATE INDEX ix_tickets_priority
    ON public.tickets(priority_id);

CREATE INDEX ix_tickets_issue_type
    ON public.tickets(issue_type_id);

CREATE INDEX ix_tickets_location
    ON public.tickets(location_id);

CREATE INDEX ix_tickets_created_at
    ON public.tickets(created_at);

CREATE INDEX ix_tickets_resolved_at
    ON public.tickets(resolved_at);

CREATE INDEX ix_comments_ticket
    ON public.comments(ticket_id);

CREATE INDEX ix_attachments_ticket
    ON public.attachments(ticket_id);

CREATE INDEX ix_assignments_ticket
    ON public.ticket_assignments(ticket_id);

CREATE INDEX ix_assignments_staff
    ON public.ticket_assignments(assigned_to);

CREATE INDEX ix_history_ticket
    ON public.ticket_history(ticket_id);

CREATE INDEX ix_notifications_user
    ON public.notifications(user_id);

CREATE INDEX ix_notifications_ticket
    ON public.notifications(ticket_id);

CREATE INDEX ix_locations_floor
    ON public.locations(floor_id);

CREATE INDEX ix_user_departments_department
    ON public.user_departments(department_id);

-- ============================================================
-- 12. SEED DATA
-- ============================================================

INSERT INTO public.roles (name) VALUES
    ('STUDENT'),
    ('DEPARTMENT_STAFF'),
    ('DEPARTMENT_ADMIN'),
    ('SYSTEM_ADMIN');

INSERT INTO public.statuses (name) VALUES
    ('NEW'),
    ('AI_PROCESSING'),
    ('NEEDS_REVIEW'),
    ('ASSIGNED'),
    ('IN_PROGRESS'),
    ('WAITING_FOR_USER'),
    ('RESOLVED'),
    ('CLOSED'),
    ('REOPENED');

INSERT INTO public.priorities (name, level) VALUES
    ('LOW', 1),
    ('MEDIUM', 2),
    ('HIGH', 3),
    ('URGENT', 4);

INSERT INTO public.departments (name, description) VALUES
    ('Facilities', 'Plumbing, electrical, HVAC, furniture, and physical campus issues'),
    ('IT', 'Wi-Fi, classroom technology, accounts, and technology issues'),
    ('Residence Life', 'Residence hall and housing-related issues'),
    ('Student Engagement', 'Clubs, events, and campus programming'),
    ('Campus Safety', 'ID, parking, safety, and related campus concerns'),
    ('Dining', 'Dining, meal plans, and swipe-related issues'),
    ('Finance', 'Financial and administrative finance-related issues'),
    ('Other / Review', 'Tickets that require manual review or cannot yet be classified');

-- ============================================================
-- NOTES
-- ============================================================
--
-- 1. departments.department_id is the EFFECTIVE/PRIMARY department.
--    ai_suggested_department_id stores what the AI recommended.
--
-- 2. The same pattern is used for issue type and priority:
--    issue_type_id / priority_id = effective value
--    ai_suggested_* = AI recommendation
--
-- 3. AI confidence is stored from 0.0000 to 1.0000.
--
-- 4. ticket_history should record important changes, including:
--      STATUS_CHANGED
--      DEPARTMENT_CHANGED
--      PRIORITY_CHANGED
--      ASSIGNED
--      UNASSIGNED
--      AI_CLASSIFIED
--      AI_OVERRIDE
--      COMMENT_ADDED
--      REOPEN_REQUESTED
--      REOPEN_APPROVED
--      REOPEN_DENIED
--      RESOLVED
--      CLOSED
--
-- 5. locations no longer stores building_id because:
--      locations -> floors -> buildings
--
-- 6. comments.is_internal allows staff notes to remain hidden from
--    students when the product requires private operational notes.
--
-- 7. deleted_at is a soft-delete marker. Do not physically delete
--    historical tickets that administrators may need for analytics/audit.
--
-- 8. Status transition rules should be enforced in the backend/service
--    layer rather than by a simple database CHECK constraint.
--
-- 9. Authorization MUST be enforced server-side. Hiding UI buttons is
--    not sufficient to prevent unauthorized access.
